apiVersion: v1
kind: ServiceAccount
metadata:
  name: guac-kubescape-collector
  namespace: guac
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: guac-kubescape-sbom-reader
  namespace: kubescape
rules:
- apiGroups:
  - spdx.softwarecomposition.kubescape.io
  resources:
  - sbomsyfts
  - sbomsyftfiltereds
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: guac-kubescape-sbom-reader
  namespace: kubescape
subjects:
- kind: ServiceAccount
  name: guac-kubescape-collector
  namespace: guac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: guac-kubescape-sbom-reader
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guac-kubescape-collector
  namespace: guac
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guac-kubescape-collector
  template:
    metadata:
      labels:
        app: guac-kubescape-collector
    spec:
      serviceAccountName: guac-kubescape-collector
      containers:
      - name: collector
        image: ghcr.io/guacsec/guac:v1.1.0
        command: ["/opt/guac/guacone"]
        args:
        - collect
        - kubescape
        - --poll
        - --kubescape-namespace=kubescape
        - --gql-addr=http://graphql-server:8080/query
        - --csub-addr=collectsub:2782
