apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - upstream/install.yaml
patches:
  - path: patches/clusterrole.yaml
  - path: patches/role.yaml
  - path: patches/delete-aggregate-exposed-secret-reports-view-clusterrole.yaml
  - path: patches/delete-aggregate-vulnerability-reports-view-clusterrole.yaml
  - path: patches/delete-aggregate-config-audit-reports-view-clusterrole.yaml
