apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - ns.yaml

images:
  - name: ghcr.io/ystkfujii/playground_supply-chain-guard/python-server
    newName: ghcr.io/ystkfujii/playground_supply-chain-guard/python-server
    newTag: stable
    digest: sha256:f4c72d8e76069a4643dd3f6568499bfd254a8c8faf5d94992b63a0fe2a70da68
