apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-server
  namespace: demo-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: ghcr.io/ystkfujii/playground_supply-chain-guard/node-server:stable@sha256:dummy 
